# Generated by Django 4.0.3 on 2022-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'В прогрессе'), (2, 'Выполнено')], default=1, max_length=100, verbose_name='Статус Задачи'),
        ),
    ]
