# Generated by Django 4.0.3 on 2022-03-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_options_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.todolist'),
            preserve_default=False,
        ),
    ]
