# Generated by Django 4.0.3 on 2022-04-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Группа задач',
                'verbose_name_plural': 'Группы задач',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateTimeField(blank=True, verbose_name='Дедлайн')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'В прогрессе'), (2, 'Выполнено')], default=1, verbose_name='Статус Задачи')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='main.todolist', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-due_date'],
            },
        ),
    ]
