# Generated by Django 4.0.3 on 2022-05-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_file_task_img_alter_task_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/', verbose_name='Изображение'),
        ),
    ]
